name: Rust Minimal

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run the CI at 02:22 UTC every Tuesday
    # We pick an arbitrary time outside of most of the world's work hours
    # to minimize the likelihood of running alongside a heavy workload.
    - cron: '22 2 * * 2'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Make new directory
        run: mkdir pixi_ws
      - name: Get pixi toml file
        run: irm https://raw.githubusercontent.com/ros2/ros2/refs/heads/rolling/pixi.toml -OutFile pixi_ws\pixi.toml
        working-directory: pixi_ws
      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@v0.8.1
      - name: Get prebuild ROS files
        run: irm https://ci.ros2.org/view/packaging/job/packaging_windows/lastSuccessfulBuild/artifact/ws/ros2-package-windows-AMD64.zip
      - name: Unzip prebuild ROS files
        run: Expand-Archive -Path ros2-package-windows-AMD64.zip -DestinationPath pixi_ws\ros2_rolling
      - name: Install Rust ROS prerequisites
        use: pip add libclang 
        working-directory: pixi_ws


        